### ISSUE TITLE
Parse recipes error : meta-kodi/recipes-multimedia/kodi/kodi-tools-texturepacker_git.bb

### ISSUE THREAD

**Issue by EzEmbedded** [koenkooi/meta-kodi#49]
I'm using meta-kodi in **Poky Container**.
**My branch is  hardknott .** 

```
git clone --depth 1 git://git.yoctoproject.org/poky -b hardknott  poky
git clone https://github.com.cnpmjs.org/superna9999/meta-meson.git -b hardknott 
git clone git://git.openembedded.org/meta-openembedded -b hardknott 
git clone git://git.yoctoproject.org/meta-virtualization -b hardknott 
git clone git://git.openembedded.org/meta-python2 -b hardknott  
git clone https://github.com.cnpmjs.org/koenkooi/meta-kodi.git -b hardknott 
```

**My BBLAYERS are:**
```
BBLAYERS ?= " \
  /home/yocto-crops/poky/meta \
  /home/yocto-crops/poky/meta-poky \
  /home/yocto-crops/poky/meta-yocto-bsp \
  /home/yocto-crops/meta-openembedded/meta-oe \
  /home/yocto-crops/meta-openembedded/meta-perl \
  /home/yocto-crops/meta-openembedded/meta-filesystems \
  /home/yocto-crops/meta-meson \
  /home/yocto-crops/meta-python2 \
  /home/yocto-crops/meta-openembedded/meta-python \
  /home/yocto-crops/meta-openembedded/meta-multimedia \
  /home/yocto-crops/meta-openembedded/meta-networking \
  /home/yocto-crops/meta-kodi \
  "
```
**My local.conf**
```
MACHINE = "seirobotics-sei610"
BB_NUMBER_THREADS = "8"
PARALLEL_MAKE = "-j 8"
LICENSE_FLAGS_WHITELIST += " commercial_mpg123 commercial commercial_libav commercial_x264 commercial"
IMAGE_INSTALL_append += " kodi"
```
**Then Run:**
> bitbake amlogic-image-headless-initrd

**The ERROR:**
```
ERROR: ExpansionError during parsing /home/yocto-crops/meta-kodi/recipes-multimedia/kodi/kodi-tools-texturepacker_git.bb
Traceback (most recent call last):
  File "/home/yocto-crops/poky/bitbake/lib/bb/fetch2/git.py", line 248, in GitSM.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f7a37832048>, d=<bb.data_smart.DataSmart object at 0x7f7a380665c0>):
                         ud.unresolvedrev[name] = ud.revisions[name]
    >                ud.revisions[name] = self.latest_revision(ud, d, name)
     
  File "/home/yocto-crops/poky/bitbake/lib/bb/fetch2/__init__.py", line 1588, in GitSM.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f7a37832048>, d=<bb.data_smart.DataSmart object at 0x7f7a380665c0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/yocto-crops/poky/bitbake/lib/bb/fetch2/git.py", line 711, in GitSM._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f7a37832048>, d=<bb.data_smart.DataSmart object at 0x7f7a380665c0>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/yocto-crops/poky/bitbake/lib/bb/fetch2/git.py", line 700, in GitSM._lsremote(ud=<bb.fetch2.FetchData object at 0x7f7a37832048>, d=<bb.data_smart.DataSmart object at 0x7f7a380665c0>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/yocto-crops/poky/bitbake/lib/bb/fetch2/__init__.py", line 896, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export PATH="/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python3-native:/home/yocto-crops/poky/scripts:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/yocto-crops/poky/bitbake/bin:/home/yocto-crops/build/tmp/hosttools"; export HOME="/home/pokyuser"; git -c core.fsyncobjectfiles=0 ls-remote https://github.com/xbmc/xbmc.git ', d=<bb.data_smart.DataSmart object at 0x7f7a37832c18>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python3-native:/home/yocto-crops/poky/scripts:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/yocto-crops/build/tmp/work/aarch64-poky-linux/kodi-tools-texturepacker/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/yocto-crops/poky/bitbake/bin:/home/yocto-crops/build/tmp/hosttools"; export HOME="/home/pokyuser"; git -c core.fsyncobjectfiles=0 ls-remote https://github.com/xbmc/xbmc.git  failed with exit code 128, output:
fatal: unable to access 'https://github.com/xbmc/xbmc.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by EzEmbedded** [comment]
I.m sorry .the error is came from my net environment.
